# Generated by Django 5.1.1 on 2024-11-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer_is_active_customer_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$c1zWKU2JOX8clLYLUdyRrC$knK+zz2DAtsBUDxs5lPCwprGSKR0ApLwPR7Hoe2c7AQ=', max_length=128),
        ),
    ]
