# Generated by Django 5.1.1 on 2024-11-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_image_store_description_store_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$bJNQgGKOSdWCgYfDkVbxbU$ThCPRDHF5MOTTHR5bTzXoPmhgDqedp5KEduG58x0OeI=', max_length=128),
        ),
    ]
