# Generated by Django 5.1.1 on 2024-11-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$rVRNi7GTAw7UxRcFHGLRIk$4iIxeio2JnYYwIshFJD35p7FCnDW2fCA4N44JMsVUHg=', max_length=128),
        ),
    ]
