# Generated by Django 5.1.1 on 2024-11-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_store_description_store_image_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$4NtOYPmaTDxonVVqmb5NoV$4XWRvNS5pyALi8MQ3+0didZS/PKfTXMHfH6IWKHjwGA=', max_length=128),
        ),
    ]
