# Generated by Django 5.1.1 on 2024-11-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$YsForFhqiH2a8Et5MvHCXt$qttqNlqu++S/BdSItyirLDEKJbfbt+1TnmKi8xXN3cc=', max_length=128),
        ),
    ]
