# Generated by Django 5.1.1 on 2024-11-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$VSmIfQoFpk6QBzJv0jv8cQ$MgjxRsB0HbYxgvZWL4I2+7FEf4tb7ODqYJ+zaze3mcM=', max_length=128),
        ),
    ]
