# Generated by Django 5.1.1 on 2024-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$EU9D22f1uLOI9osSt8TQVF$N4ZSye48b4UV3fL23TiBz9Cn2FlRa274ZYGfo3tAaZo=', max_length=128),
        ),
    ]
