# Generated by Django 5.1.1 on 2024-11-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$dX5ZPCXHbh3AQz5z4znYVk$4Qp136VzixuXdLcdRxLBMq/mrPBR63TOfgPTDWj1ikw=', max_length=128),
        ),
    ]
