# Generated by Django 5.1.1 on 2024-11-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$6nTc10uJvMC0HqkmXbdztj$1izzCzS9c1tS5Vel5DFIzIzTEPKRSYutitHsgMoeGEM=', max_length=128),
        ),
    ]
