# Generated by Django 5.1.1 on 2024-11-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$XsBtcyr7E4xtG1psbcj4Jj$GGpdzDu6U8kGg7ulwCKxU4cFkyyYKgBry9ViRSHDhZU=', max_length=128),
        ),
    ]
