# Generated by Django 5.1.1 on 2024-11-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$hFAIncLdXJSugLW73wcyHG$E8msPLF7/TbLg0H8Naz+1J8XF1ZmfXLl0X7wNgm40wk=', max_length=128),
        ),
    ]
