# Generated by Django 5.1.1 on 2024-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$FCkr3lH3zYCUWUTUQqhH95$3qS8vPwiIVFTTKL/0+BLxObRifJaLH6I3pXsIolHGXg=', max_length=128),
        ),
    ]
