# Generated by Django 5.1.1 on 2024-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$II1Tm3x23Zh6P2isLdhg25$8vykugrQTKySodTYfKfLG+oMcBowJ/s7gmZFFWZdfiU=', max_length=128),
        ),
    ]
