# Generated by Django 5.1.3 on 2024-11-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$FWsvbAP4ztSZwKCSSyWatL$FCIL1upP1iN5cjrmREOFXuMybV/Yi/7UGx0ScKnSsFg=', max_length=128),
        ),
    ]
