# Generated by Django 5.1.1 on 2024-11-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$21Fi2D3UBDiCVHGUwyZrPR$/2gNcR38trDpK0gzsE1R5mc4PQ87Cel30/mWFnJkH0c=', max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
