# Generated by Django 5.1.3 on 2024-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_type_category_name_alter_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$622RrixhThYJB631P6IpL0$57eZDd+4u9dLhDdMwcMeLpVpCNxMh89SiEqQY0waV3k=', max_length=128),
        ),
    ]
