# Generated by Django 5.1.3 on 2024-11-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_category_type_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$BPAXBiAOuW4RSsBjsAi1S6$vZC7nR8ap6caNstKxCAlEwLnQqlq0Zj+ZGrpZzgbLNI=', max_length=128),
        ),
    ]
