# Generated by Django 5.1.1 on 2024-11-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_image_product_price_product_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$wnbGeB9tGWlnuuUegK6lI5$f+2kXM3zFIc2giDrVFZwtyamx6zbn7FEDq+0yKCBOyk=', max_length=128),
        ),
    ]
