# Generated by Django 5.1.3 on 2024-11-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$VuwloiNe1nkMKyMnx9F9iH$Bp7aT6PnWKHDXlsUH7EFQE7FK+F/xEWrUk86AYAydg8=', max_length=128),
        ),
    ]
