# Generated by Django 5.1.1 on 2024-12-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ad_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$b7ufa8Qw1eVuP6zXLvo1aa$w0kAbvp/mHFRg0hncSXt9Zqk7hRj1gT4izv0iIvmKWg=', max_length=128),
        ),
    ]
