# Generated by Django 5.1.1 on 2024-11-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customer_groups_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$bqOn2sWC5wySRKNOl4sGRa$nEEGq9m9ZNQHGgB56ZjsmpWSoF2OEwpt3lYHcuADR9I=', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.store'),
        ),
    ]
