# Generated by Django 5.1.3 on 2024-12-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ad_image_alter_ad_name_alter_customer_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$MoNsCtICzGFsPYrtQPiv7h$YBJWh3eLDNN5kd6GK5qtBg8msO+rRESJOMqRCMUrfyQ=', max_length=128),
        ),
    ]
