# Generated by Django 5.1.1 on 2024-11-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_customer_password_alter_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/products/default.jpg', upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$di4xek8MfY98NVvei49VLJ$HzqK0DIyc1FWxt2EoNroZ+Ucr/NNxz6jl60ZXk+wH3Q=', max_length=128),
        ),
    ]
