# Generated by Django 5.1.1 on 2024-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_image_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$eVht4Kwl0sneYYR4c75ASU$cynxzudwqZkwyllSJDoJR0JMVMe5Oo2E6Me7sv+bWWs=', max_length=128),
        ),
    ]
