# Generated by Django 5.1.1 on 2024-11-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$jr86XpZhg0htzs09NkkHqY$FqAGPxR1hr0ij4uvkeyk0XAcIRnc+oHd336+G5G4xoo=', max_length=128),
        ),
    ]
