# Generated by Django 5.1.1 on 2024-11-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category_image_store_description_store_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$8zfF5oZrrz1kd3iU3L7juJ$vCNQCp6cMVtvDfXrHB6wMQ2FAsewNse/MNfn6XYE1AQ=', max_length=128),
        ),
    ]
