# Generated by Django 5.1.1 on 2024-11-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$fs84BMqYt3twVS2wOLQSrm$RByPC0EvGSGgHP06nw3NOu988SjgVLk4izKjzZdMlwE=', max_length=128),
        ),
    ]
