# Generated by Django 5.1.3 on 2024-11-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$hGBIrZoqkB9MUxf1ug7kQ5$1PIEnjYWecJfY1ZzKxbdL3tMWJvAdjbmXgeYFbgBs3A=', max_length=128),
        ),
    ]
