# Generated by Django 5.1.3 on 2024-11-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Lk09JZ7r9L6lVDct9x9Czw$eIqB7qIq319xtdYkXGu8Eqcj0/goxmdFTzwJ9UG7SpQ=', max_length=128),
        ),
    ]
